version: "3"

services:
  furyaprotocold0:
    image: local:furyaprotocol
    entrypoint:
      - cosmovisor
      - run
      - start
      - --log_level
      # Note that only this validator has a log-level of `info`; other validators use `error` by default.
      # Change to `debug` for more verbose log-level.
      - info
      - --home
      - /furyaprotocol/chain/.alice
      - --p2p.persistent_peers
      - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@furyaprotocold0:26656,b69182310be02559483e42c77b7b104352713166@furyaprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@furyaprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@furyaprotocold3:26656"
      - --bridge-daemon-eth-rpc-endpoint
      - "${ETH_RPC_ENDPOINT}"
      - --dd-error-tracking-format
      - "true"
      - --max-daemon-unhealthy-seconds
      - "4294967295" # Effectively disable the daemon monitor because bridge daemon is flaky in localnet.
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/furyaprotocol/chain/.alice
    volumes:
      - ./localnet/furyaprotocol0:/furyaprotocol/chain/.alice/data
    ports:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"

  furyaprotocold1:
    image: local:furyaprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /furyaprotocol/chain/.bob
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@furyaprotocold0:26656,b69182310be02559483e42c77b7b104352713166@furyaprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@furyaprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@furyaprotocold3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/furyaprotocol/chain/.bob
    volumes:
      - ./localnet/furyaprotocol1:/furyaprotocol/chain/.bob/data
    ports:
      - "26658:26657"

  furyaprotocold2:
    image: local:furyaprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /furyaprotocol/chain/.carl
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@furyaprotocold0:26656,b69182310be02559483e42c77b7b104352713166@furyaprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@furyaprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@furyaprotocold3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/furyaprotocol/chain/.carl
    volumes:
      - ./localnet/furyaprotocol2:/furyaprotocol/chain/.carl/data

  furyaprotocold3:
    image: local:furyaprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /furyaprotocol/chain/.dave
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@furyaprotocold0:26656,b69182310be02559483e42c77b7b104352713166@furyaprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@furyaprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@furyaprotocold3:26656"
       - --bridge-daemon-eth-rpc-endpoint
       - "${ETH_RPC_ENDPOINT}"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/furyaprotocol/chain/.dave
    volumes:
      - ./localnet/furyaprotocol3:/furyaprotocol/chain/.dave/data

  datadog-agent:
    image: datadog/agent:7
    environment:
      # See https://docs.datadoghq.com/containers/docker/?tab=standard#environment-variables for agent configuration
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8125:8215"
      - "8126:8126"
