FROM furyaprotocol-base

COPY ./testing/snapshotting/snapshot.sh /furyaprotocol/snapshot.sh

RUN go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@v1.4.0

ENTRYPOINT ["/furyaprotocol/snapshot.sh"]
